#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pizza.h"

int main(){
	ArvBM arvPizza;
	strcpy(arvPizza.nome, "pizzas");
	deleta_arv(arvPizza);
	arvPizza = cria_arvore("pizzas", 2);
	arvPizza = insere_arv_parametros(arvPizza, 10, 30.0, "Calabresa", "Salgada");
    printf("Inseriu 10:\n");
	imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
	arvPizza = insere_arv_parametros(arvPizza, 15, 32.0, "Bianca", "Salgada");
    printf("Inseriu 15:\n");
	imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
	arvPizza = insere_arv_parametros(arvPizza ,18, 40.0, "Estrogonoff com Cogumelos", "Especial");
    printf("Inseriu 18:\n");
	imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
	arvPizza = insere_arv_parametros(arvPizza ,25, 25.0, "Banana", "Doce");
    printf("Inseriu 25:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,30, 25.0, "Banana", "Doce");
    printf("Inseriu 30:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,27, 25.0, "Banana", "Doce");
    printf("Inseriu 27:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,28, 25.0, "Banana", "Doce");
    printf("Inseriu 28:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,7, 25.0, "Banana", "Doce");
    printf("Inseriu 7:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,12, 25.0, "Banana", "Doce");
    printf("Inseriu 12:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    arvPizza = insere_arv_parametros(arvPizza ,99, 25.0, "Banana", "Doce");
    printf("Inseriu 99:\n");
    imprime_prox("pizzas/pizzas0", 0);
    imprime_prox("pizzas/pizzas2", 2);
    imprime_prox("pizzas/pizzas3", 3);
    imprime_prox("pizzas/pizzas4", 4);
    imprime(arvPizza);
    printf("-------------------------------\n");
    //printf("I0:\n");
    //imprime_interno("pizzas/pizzas0");
    printf("I5:\n");
    imprime_interno("pizzas/pizzas5");
    printf("I1:\n");
    imprime_interno("pizzas/pizzas1");
    //printf("I2:\n");
    //imprime_interno("pizzas/pizzas2");
    //printf("I3:\n");
    //imprime_interno("pizzas/pizzas3");
    //printf("I4:\n");
    //imprime_interno("pizzas/pizzas4");
    printf("I6:\n");
    imprime_interno("pizzas/pizzas6");
    printf("-------------------------------\n");
    printf("F0\n");
    imprime_folha("pizzas/pizzas0");
    //printf("F1\n");
    //imprime_folha("pizzas/pizzas1");
    printf("F4\n");
    imprime_folha("pizzas/pizzas4");
    printf("F2\n");
    imprime_folha("pizzas/pizzas2");
    printf("F3\n");
    imprime_folha("pizzas/pizzas3");
    /*printf("F5\n");
    imprime_folha("pizzas/pizzas5");
    printf("F6\n");
    imprime_folha("pizzas/pizzas6");*/
	//imprime(arvPizza);
	return 0;
}
